---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
Unzip data to obtain a csv file.   
```{r}
library("data.table")
library(ggplot2)
      
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(fileUrl, destfile = paste0(getwd(), '/repdata%2Fdata%2Factivity.zip'), method = "curl")
unzip("repdata%2Fdata%2Factivity.zip",exdir = "data")
```


## What is mean total number of steps taken per day?
```{r}
activityDT <- data.table::fread(input = "data/activity.csv")
```


## What is the average daily activity pattern?
```{r}
IntervalDT <- activityDT[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval)] 
ggplot(IntervalDT, aes(x = interval , y = steps)) + 
geom_line(size=1) + labs(title = "Average Daily Steps", x = "Interval", y = "Average Steps per day") + theme(plot.title = element_text(hjust = 0.5))
```


## Imputing missing values
```{r}
nrow(activityDT[is.na(steps),])
activityDT[is.na(steps), "steps"] <- activityDT[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
```
      
## Are there differences in activity patterns between weekdays and weekends?
```{r}
IntervalDT <- activityDT[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval, `weekday or weekend`)] 
ggplot(IntervalDT , aes(x = interval , y = steps, color=`weekday or weekend`)) + 
geom_line() + 
labs(title = "Average Daily Steps by Weektype", x = "Interval", y = "No. of Steps") + facet_wrap(~`weekday or weekend` , ncol = 1, nrow=2) + theme(plot.title = element_text(hjust = 0.5))  
```
